# Row reduction and LU decomposition

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# sympy library for RREF
import sympy as sym

# scipy for LU
import scipy.linalg


# used to create non-regular subplots
import matplotlib.gridspec as gridspec


# NOTE: these lines define global figure properties used for publication.
import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg') # display figures in vector format
plt.rcParams.update({'font.size':14}) # set global font size

## 9.1 System of equations

### 9.1.1 Convert system of equations into matrix

### 9.1.2. Matrix equations

In [3]:
# generate some matrices
A = np.random.randn(4,4)
B = np.random.randn(4,4)

# solve for X
# 1) inv(A)@A@X = inv(A)@B
# 2) inv(A)@A@X = B@inv(A)

X1 = np.linalg.inv(A) @ B
X2 = B @ np.linalg.inv(A)

# residual (should be zeros matrix)
res1 = A@X1 - B
res2 = A@X2 - B

# which is correct?
print('res1:'), print(' ')
print( np.round(res1,10) ), print(' ')

print('res2:'), print(' ')
print( np.round(res2,10) )


res1:
 
[[ 0.  0. -0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -0.  0.]
 [-0. -0.  0. -0.]]
 
res2:
 
[[-0.74760298  2.08506536  3.53037833  1.73187477]
 [-2.54403187  1.51457142  2.83150255 -0.94825605]
 [ 1.82495167 -0.33276905  1.3356465   4.47916679]
 [-0.0735937   2.26461382  0.18267889 -2.10261494]]


## 9.2 Row reduction 
- 행렬의 행에 스칼라 곱셈과 덧셈이라는 두가지 연산을 반복적으로 적용하는 것
- 하나의 연립방정식 내에서 하나의 방정식을 다른 방정식에 더하는 것과 동일한 원리를 사용한다
- 행축소의 목표는 밀집행렬(dense matrix)을 상삼각 행렬로 변환하는것이다

### 9.2.1. Gaussian elimination 
1) 계수 행렬을 상수 벡터로 증강하고
2) 행을 사다리꼴 형태로 축소한 다음
3) 역치환(back substitution)을 사용하여 각 변수를 차례로 푼다

### 9.2.2 Gauss-Jordan Elimination(RREF)

In [6]:
# The augmented matrix
M = np.array( [[ 1, 1, 4], [-1/2, 1, 2] ])

# Converted into a sympy matrix
symMat = sym.Matrix(M)
print((symMat))

# RREF
symMat.rref()[0]

Matrix([[1.00000000000000, 1.00000000000000, 4.00000000000000], [-0.500000000000000, 1.00000000000000, 2.00000000000000]])


Matrix([
[1, 0, 1.33333333333333],
[0, 1, 2.66666666666667]])

### 9.2.3. Inverse matrix calcuation by Gauss-Jordan Elimination
- 연립방정식을 푸는 선형 변환에 대한 설명과 일치한다
- 가우스 조던 소거법을 이용해 역행렬을 계산하는 것이 완전 역행렬 알고리즘 보다 수치적으로 더 안정적일 수 있지만,
특이 행렬에 가깝거나 조건수가 높은 행렬이라면 사용되는 알고리즘에 관계없이 역을 구하기 어렵다

## 9.3 LU decompositition
- 두개의 삼각 행렬의 곱으로 분해하는 것(lower, upper)

In [10]:
# simple example with integers

# a matrix
A = np.array( [[2, 2, 4], [1, 0, 3], [2, 1, 2]])

# its LU decomposition via scipy (please ignore the first output for now)
_, L, U = scipy.linalg.lu(A)

print('L: ')
print(L), print(' ')

print('U: ')
print(U), print(' ')

print('A - LU: ')
print(A - L@U) # should be zeros

L: 
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]]
 
U: 
[[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]
 
A - LU: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 9.3.1 Using exchange using permutation matrix 치환 행렬
- 행 교환은 행 축소 기법중에 하나로, 치환 행렬을 통해서 구현할 수 있음
- 치환 행렬은 모든 원소가 0이거나 1이고, 행은 한번만 교한되므로 정확히 하나의 0이 아닌 원소만 존재하므로 inverse p = transpose p