# Vector and basic calculation of vector

In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt


# NOTE: these lines define global figure properties used for publication.
import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg') # display figures in vector format
plt.rcParams.update({'font.size':14}) # set global font size

## 1.1 Creating vectors

In [10]:
asList = [1,2,3]
asArray = np.array([1,2,3])

rowVec = np.array([ [1, 2, 3]   ]) #row     #inner brakect set means rows
colVec = np.array([[1], [2], [3]]) #column
rowVec, colVec

(array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]))

In [12]:
np.array([[1, 2], [2,3 ], [3,4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [ ]:
# Check the sizes of the variables
print(f'asList:  {np.shape(asList)}') 
print(f'asArray: {asArray.shape}') 
print(f"rowVec : {rowVec.shape}")
print(f"colwVec : {colVec.shape}")

asList:  (3,)
asArray: (3,)
rowVec : (1, 3)
colwVec : (3, 1)


## 1.2 Vector operations 

### 1.2.1 Adding vector
- Two vectors can be added only when they have the same dimension and direction.

### 1.2.3 Vector-scalar multiplication

In [13]:
s = 2
a = [3, 4, 5] # list
b = np.array(a)
print(a*s)  # Repetition of list 
print(b*s)  # Vector-scalar ⭐️

[3, 4, 5, 3, 4, 5]
[ 6  8 10]


### 1.2.5. Transpose

In [ ]:
# Row vector
r = np.array([ [1,2,3] ])

# orientationless array
l = np.array([1,2,3])

In [18]:
# print out the vector, its transpose, and its double-transpose
print(r), print(' ')

# Transpose the row vector
print(r.T), print(' ')

# double-transpose
print(r.T.T)
     

[[1 2 3]]
 
[[1]
 [2]
 [3]]
 
[[1 2 3]]


In [19]:
# Same for the orientationless array
print(l), print(' ')
print(l.T), print(' ')
print(l.T.T)

[1 2 3]
 
[1 2 3]
 
[1 2 3]


### 1.2.6 Broadcasting on Python

In [22]:
v = np.array([[ 1,2,3]]).T
w = np.array([[ 10, 20 ]])
v+w 

array([[11, 21],
       [12, 22],
       [13, 23]])

In [24]:
np.array([[ 1,2,3]]).T

array([[1],
       [2],
       [3]])

## 1.3 Magnitude of a vector(norm) and unit vector

In [27]:
v = np.array([1,2,3,7,8,9])
v_dim = len(v) # dimention
v_mag = np.linalg.norm(v) #norm
v_dim, v_mag

(6, 14.422205101855956)

## 1.4 Vector-dot product
- 하나의 숫자로 두 벡터 사이의 관계를 나타낸다
- 두 벡터에서 대응되는 원소끼리 곱한 다음 모든 결과를 더한다
- 동일한 차원의 두 벡터에서만 성립한다

----------------------------------------------------------

- 내적은 두 벡터 사이의 유사성(similarity) 또는 매핑(mapping)의 척도로 해석

In [28]:
v = np.array([1, 2, 3, 4])
w = np.array([5, 6, 7, 8])
np.dot(v,w)

70

In [29]:
s = 10
np.dot(s*v, w)

700

### 1.4.1 The dot product is distributive

In [30]:
# just some random vectors...
v = np.array([ 0,1,2 ])
w = np.array([ 3,5,8 ])
u = np.array([ 13,21,34 ])


# two ways to compute
res1 = np.dot( v, w+u )
res2 = np.dot( v, w) + np.dot(v, u)

res1, res2

(110, 110)